matrix:
    include:
        - language: node_js
          node_js:
              - '11'
          sudo: false
          cache: npm
          before_install:
              - cd server
          install:
              - npm ci
          script:
              - npm run lint:check
        - language: android
          android:
              components:
                  - tools
                  - build-tools-28.0.3
                  - android-28
          before_script:
              - cd client
          script:
              - ./gradlew build connectedCheck
