name: cell-wall
private: true
version: 4.1.0
scripts:
  start: node javascript/server/build/index.js
  lint: >-
    prettier --check .prettierrc {package,pnpm-workspace}.yaml *.md
    .github/**/*.yml
  format: >-
    prettier --write .prettierrc {package,pnpm-workspace}.yaml *.md
    .github/**/*.yml
devDependencies:
  '@typescript-eslint/eslint-plugin': ^7.15.0
  '@typescript-eslint/parser': ^7.15.0
  eslint: ^8.57.0
  eslint-config-prettier: ^9.1.0
  prettier: ~3.3.2
  typescript: ^5.5.3
engines:
  node: '>=20.0.0'
  pnpm: '>=8.0.0'
