name: cell-wall
private: true
version: 4.0.0
scripts:
  build: >-
    pnpm run build --filter @cell-wall/client && pnpm run build --filter @cell-wall/server
  start: node javascript/server/build/index.js
  lint: prettier --check .prettierrc {package,pnpm-workspace}.yaml *.md .github/**/*.yml
  format: prettier --write .prettierrc {package,pnpm-workspace}.yaml *.md .github/**/*.yml
devDependencies:
  prettier: '~2.4.1'
engines:
  node: '>=16.10.0'
  pnpm: '>=6.16.0'
