name: cell-wall
private: true
version: 4.1.0
scripts:
  start: node javascript/server/build/index.js
  lint: >-
    prettier --check .prettierrc {package,pnpm-workspace}.yaml *.md
    .github/**/*.yml
  format: >-
    prettier --write .prettierrc {package,pnpm-workspace}.yaml *.md
    .github/**/*.yml
devDependencies:
  '@typescript-eslint/eslint-plugin': ^6.2.1
  '@typescript-eslint/parser': ^6.2.1
  eslint: ^8.46.0
  eslint-config-prettier: ^9.0.0
  prettier: ~3.0.1
  typescript: ^5.1.6
engines:
  node: '>=20.0.0'
  pnpm: '>=8.0.0'
