name: cell-wall
private: true
version: 4.1.0
scripts:
  start: node javascript/server/build/index.js
  lint: >-
    prettier --check .prettierrc {package,pnpm-workspace}.yaml *.md
    .github/**/*.yml
  format: >-
    prettier --write .prettierrc {package,pnpm-workspace}.yaml *.md
    .github/**/*.yml
devDependencies:
  '@typescript-eslint/eslint-plugin': ^5.26.0
  '@typescript-eslint/parser': ^5.26.0
  eslint: ^8.16.0
  eslint-config-prettier: ^8.5.0
  prettier: ~2.6.2
  typescript: ^4.7.2
engines:
  node: '>=16.10.0'
  pnpm: '>=6.16.0'
