POST http://raspberrypi.local:3000/v3/device/power
content-type: application/json

{
  "on": true
}

###

POST http://raspberrypi.local:3000/v3/device/power
content-type: application/json

{
  "on": false
}
