POST http://raspberrypi.local:3000/v3/device/state
content-type: application/json

{
  "93HAY0BJ0G": {
    "type": "WEB",
    "url": "/page/text?text=Blueberry+White+Peony&backgroundColor=%239BA1B5",
    "text": "Blueberry White Peony",
    "backgroundColor": "#9BA1B5"
  },
  "TA880004ZI": {
    "type": "WEB",
    "url": "/page/text?text=Mana+Assam&backgroundColor=%23B0513F",
    "text": "Mana Assam",
    "backgroundColor": "#B0513F"
  },
  "TA880007GH": {
    "type": "TEXT",
    "url": "/page/text?text=Jasmine&backgroundColor=%23B9BB66",
    "text": "Jasmine",
    "backgroundColor": "#B9BB66"
  },
  "4e50f5bd": {
    "type": "WEB",
    "url": "/page/text?text=Kashi+Ginger&backgroundColor=%235072AB",
    "text": "Kashi Ginger",
    "backgroundColor": "#5072AB"
  },
  "D01EC0A0201512ER": {
    "type": "TEXT",
    "text": "Genmaicha, Hojicha",
    "backgroundColor": "#B9BB66"
  }
}

###
