name: Build APK

on:
  push:
    branches: [main]

jobs:
  apk:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
      - run: ./gradlew assembleDebug --stacktrace
        name: build apk
        working-directory: ./android
      - name: release apk
        uses: softprops/action-gh-release@v1
        with:
          files: android/app/build/outputs/apk/debug/app-debug.apk
