name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew lintDebug
        working-directory: ./android
      - uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: android/app/build/reports/lint-results-debug.html
          if-no-files-found: error
      # - run: ./gradlew testDebugUnitTest
      #   working-directory: ./android

  javascript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'

      - name: pnpm cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: pnpm install
        uses: pnpm/action-setup@v1.2.1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          version: 5.13.5
          run_install: |
            - recursive: true

      - run: pnpm recursive test
