name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
      - run: ./gradlew lintDebug
        name: lint
        working-directory: ./android
      - uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: android/app/build/reports/lint-results-debug.html
          if-no-files-found: error
      # - run: ./gradlew testDebugUnitTest
      #   working-directory: ./android

  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.x.x

      # Install dependencies
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: pnpm
          cache-dependency-path: server/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile

      # Validate the source code
      - run: pnpm run lint
      - run: pnpm run check
      - run: pnpm run test

      # Build production code
      - run: pnpm run build
      - run: cp ./{package.json,pnpm-lock.yaml,.gitignore} ./build

      # Publish the code
      - name: deploy to branch
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./server/build
          publish_branch: pi-deploy
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
