name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: ./gradlew lintDebug
        name: lint
        working-directory: ./android
      - uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: android/app/build/reports/lint-results-debug.html
          if-no-files-found: error
      # - run: ./gradlew testDebugUnitTest
      #   working-directory: ./android

  javascript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.x.x

      # Install dependencies
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install -r

      # Validate the source code
      - run: pnpm run lint -r
      - run: pnpm run check -r
      - run: pnpm run test -r

      # Build production code
      - run: pnpm run build -r

      - uses: actions/upload-artifact@v2
        with:
          name: javascript-build
          if-no-files-found: error
          path: |
            javascript/client/build/
            javascript/client/package.json
            javascript/server/build/
            javascript/server/.gitignore
            javascript/server/package.json
            javascript/shared/src/
            javascript/shared/package.json
            deploy.gitignore
            pnpm-lock.yaml
            pnpm-workspace.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: javascript

    steps:
      - uses: actions/checkout@v2
        with:
          ref: pi-deploy

      # Update files to latest build
      - run: rm -rf javascript
      - uses: actions/download-artifact@v2
        with:
          name: javascript-build
      - run: mv deploy.gitignore .gitignore

      # Deploy to pi-deploy branch
      - uses: EndBug/add-and-commit@v7
        with:
          branch: pi-deploy
          message: '${{ github.event.head_commit.message }}'
          pull: NO-PULL
          push: true
